# Generated by Django 5.1.5 on 2025-03-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('reg_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('program_name', models.CharField(choices=[('DCIVIL', 'DCIVIL'), ('DMECH', 'DMECH'), ('DEEE', 'DEEE'), ('DECE', 'DECE'), ('DCSE', 'DCSE'), ('DMX', 'DMX'), ('DMT', 'DMT')], max_length=10)),
                ('program_type', models.CharField(choices=[('Regular', 'Regular'), ('Lateral', 'Lateral')], max_length=10)),
                ('year_of_joining', models.DateField(blank=True, null=True)),
                ('mentor_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Others', 'Others')], max_length=10)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True)),
                ('mother_tongue', models.CharField(blank=True, max_length=50, null=True)),
                ('differently_abled', models.CharField(max_length=5)),
                ('mobile_father', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile_mother', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile_sibling', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile_guardian', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('emis_number', models.CharField(blank=True, max_length=20, null=True)),
                ('sslc_mark', models.IntegerField()),
                ('hsc_iti_mark', models.IntegerField(blank=True, null=True)),
                ('govt_school', models.CharField(max_length=5)),
                ('first_graduate', models.CharField(max_length=5)),
                ('hosteller', models.CharField(max_length=5)),
                ('single_parent', models.CharField(max_length=5)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=15, null=True)),
                ('extra_curricular', models.TextField(blank=True, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('religion', models.CharField(blank=True, choices=[('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Islam', 'Islam'), ('Other', 'Other')], max_length=10, null=True)),
                ('community', models.CharField(blank=True, choices=[('BC', 'BC'), ('MBC', 'MBC'), ('SC', 'SC'), ('ST', 'ST'), ('OC', 'OC')], max_length=5, null=True)),
            ],
        ),
    ]
