# Generated by Django 5.1.5 on 2025-03-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_student_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='differently_abled',
            field=models.BooleanField(default='No'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_graduate',
            field=models.BooleanField(default='No'),
        ),
        migrations.AlterField(
            model_name='student',
            name='govt_school',
            field=models.BooleanField(default='No'),
        ),
        migrations.AlterField(
            model_name='student',
            name='hosteller',
            field=models.BooleanField(default='No'),
        ),
        migrations.AlterField(
            model_name='student',
            name='single_parent',
            field=models.BooleanField(default='No'),
        ),
    ]
