# Generated by Django 5.1.5 on 2025-03-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_student_differently_abled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='program_name',
            field=models.CharField(choices=[('DCIVIL', 'DCIVIL'), ('DMECH', 'DMECH'), ('DEEE', 'DEEE'), ('DECE', 'DECE'), ('DCSE', 'DCSE'), ('DMX', 'DMX'), ('DMT', 'DMT')], max_length=10),
        ),
    ]
