# Generated by Django 5.1.5 on 2025-05-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_hscmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITIMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=20, unique=True)),
                ('dob', models.DateField()),
                ('subject_1', models.IntegerField()),
                ('subject_2', models.IntegerField()),
                ('subject_3', models.IntegerField()),
                ('subject_4', models.IntegerField()),
                ('subject_5', models.IntegerField()),
                ('subject_6', models.IntegerField()),
                ('total', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('result', models.CharField(max_length=10)),
            ],
        ),
    ]
