# Generated by Django 5.1.5 on 2025-05-08 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_itimark'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1', '1 Semester'), ('2', '2 Semester'), ('3', '3 Semester'), ('4', '4 Semester'), ('5', '5 Semester'), ('6', '6 Semester')], max_length=2)),
                ('subject1', models.IntegerField()),
                ('subject2', models.IntegerField()),
                ('subject3', models.IntegerField()),
                ('subject4', models.IntegerField()),
                ('subject5', models.IntegerField()),
                ('subject6', models.IntegerField()),
                ('subject7', models.IntegerField()),
                ('result', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
