# Generated by Django 5.1.5 on 2025-03-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_student_dob_alter_student_year_of_joining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reg_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
