# Generated by Django 5.1.5 on 2025-02-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('dcivil', 'DCIVIL'), ('dmech', 'DMECH'), ('deee', 'DEEE'), ('dece', 'DECE'), ('dcse', 'DCSE'), ('dmx', 'DMX')], max_length=10)),
                ('user_category', models.CharField(choices=[('teacher', 'Teacher')], max_length=10)),
            ],
        ),
    ]
