# Generated by Django 5.1.5 on 2025-03-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('DCIVIL', 'DCIVIL'), ('DMECH', 'DMECH'), ('DEEE', 'DEEE'), ('DECE', 'DECE'), ('DCSE', 'DCSE'), ('DMX', 'DMX'), ('DMT', 'DMT'), ('OTHERS', 'OTHERS')], max_length=10),
        ),
    ]
