# Generated by Django 5.1.5 on 2025-03-04 13:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
