# Generated by Django 5.1.5 on 2025-03-29 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_userprofile_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUser',
        ),
    ]
