# Generated by Django 5.1.5 on 2025-03-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_userprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('dcivil', 'DCIVIL'), ('dmech', 'DMECH'), ('deee', 'DEEE'), ('dece', 'DECE'), ('dcse', 'DCSE'), ('dmx', 'DMX'), ('dmt', 'DMT')], max_length=10),
        ),
    ]
