# Generated by Django 5.1.5 on 2025-03-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_authuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_category',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('others', 'Others')], default='Female', max_length=10),
        ),
    ]
