# Generated by Django 5.1.5 on 2025-03-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_userprofile_user_category_userprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
    ]
