# Generated by Django 5.1.5 on 2025-03-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('others', 'Others')], default='Female', max_length=10),
        ),
    ]
